// src/components/EmojiSearch.jsx
import {motion} from 'framer-motion';
import React, { useState } from 'react';

const emojiList = [
  // Smileys & Emotion
  { symbol: '😀', name: 'Grinning Face', category: 'Smileys & Emotion' },
  { symbol: '😃', name: 'Grinning Face with Big Eyes', category: 'Smileys & Emotion' },
  { symbol: '😄', name: 'Grinning Face with Smiling Eyes', category: 'Smileys & Emotion' },
  { symbol: '😁', name: 'Beaming Face with Smiling Eyes', category: 'Smileys & Emotion' },
  { symbol: '😆', name: 'Grinning Squinting Face', category: 'Smileys & Emotion' },
  { symbol: '😅', name: 'Grinning Face with Sweat', category: 'Smileys & Emotion' },
  { symbol: '😂', name: 'Face with Tears of Joy', category: 'Smileys & Emotion' },
  { symbol: '🤣', name: 'Rolling on the Floor Laughing', category: 'Smileys & Emotion' },
  { symbol: '😊', name: 'Smiling Face with Smiling Eyes', category: 'Smileys & Emotion' },
  { symbol: '😇', name: 'Smiling Face with Halo', category: 'Smileys & Emotion' },
  { symbol: '🙂', name: 'Slightly Smiling Face', category: 'Smileys & Emotion' },
  { symbol: '🙃', name: 'Upside-Down Face', category: 'Smileys & Emotion' },
  { symbol: '😉', name: 'Winking Face', category: 'Smileys & Emotion' },
  { symbol: '😌', name: 'Relieved Face', category: 'Smileys & Emotion' },
  { symbol: '😍', name: 'Smiling Face with Heart-Eyes', category: 'Smileys & Emotion' },
  { symbol: '🥰', name: 'Smiling Face with Hearts', category: 'Smileys & Emotion' },
  { symbol: '😘', name: 'Face Blowing a Kiss', category: 'Smileys & Emotion' },
  { symbol: '😗', name: 'Kissing Face', category: 'Smileys & Emotion' },
  { symbol: '😙', name: 'Kissing Face with Smiling Eyes', category: 'Smileys & Emotion' },
  { symbol: '😚', name: 'Kissing Face with Closed Eyes', category: 'Smileys & Emotion' },
  { symbol: '😋', name: 'Face Savoring Food', category: 'Smileys & Emotion' },
  { symbol: '😛', name: 'Face with Tongue', category: 'Smileys & Emotion' },
  { symbol: '😜', name: 'Winking Face with Tongue', category: 'Smileys & Emotion' },
  { symbol: '🤪', name: 'Zany Face', category: 'Smileys & Emotion' },
  { symbol: '😝', name: 'Squinting Face with Tongue', category: 'Smileys & Emotion' },
  { symbol: '🤑', name: 'Money-Mouth Face', category: 'Smileys & Emotion' },
  { symbol: '🤗', name: 'Hugging Face', category: 'Smileys & Emotion' },
  { symbol: '🤭', name: 'Face with Hand Over Mouth', category: 'Smileys & Emotion' },
  { symbol: '🤫', name: 'Shushing Face', category: 'Smileys & Emotion' },
  { symbol: '🤔', name: 'Thinking Face', category: 'Smileys & Emotion' },
  { symbol: '🤐', name: 'Zipper-Mouth Face', category: 'Smileys & Emotion' },
  { symbol: '🤨', name: 'Face with Raised Eyebrow', category: 'Smileys & Emotion' },
  { symbol: '😐', name: 'Neutral Face', category: 'Smileys & Emotion' },
  { symbol: '😑', name: 'Expressionless Face', category: 'Smileys & Emotion' },
  { symbol: '😶', name: 'Face Without Mouth', category: 'Smileys & Emotion' },
  { symbol: '😏', name: 'Smirking Face', category: 'Smileys & Emotion' },
  { symbol: '😒', name: 'Unamused Face', category: 'Smileys & Emotion' },
  { symbol: '🙄', name: 'Face with Rolling Eyes', category: 'Smileys & Emotion' },
  { symbol: '😬', name: 'Grimacing Face', category: 'Smileys & Emotion' },
  { symbol: '🤥', name: 'Lying Face', category: 'Smileys & Emotion' },
  { symbol: '😔', name: 'Pensive Face', category: 'Smileys & Emotion' },
  { symbol: '😪', name: 'Sleepy Face', category: 'Smileys & Emotion' },
  { symbol: '🤤', name: 'Drooling Face', category: 'Smileys & Emotion' },
  { symbol: '😴', name: 'Sleeping Face', category: 'Smileys & Emotion' },
  { symbol: '😷', name: 'Face with Medical Mask', category: 'Smileys & Emotion' },
  { symbol: '🤒', name: 'Face with Thermometer', category: 'Smileys & Emotion' },
  { symbol: '🤕', name: 'Face with Head-Bandage', category: 'Smileys & Emotion' },
  { symbol: '🤢', name: 'Nauseated Face', category: 'Smileys & Emotion' },
  { symbol: '🤮', name: 'Face Vomiting', category: 'Smileys & Emotion' },
  { symbol: '🤧', name: 'Sneezing Face', category: 'Smileys & Emotion' },
  { symbol: '🥵', name: 'Hot Face', category: 'Smileys & Emotion' },
  { symbol: '🥶', name: 'Cold Face', category: 'Smileys & Emotion' },
  { symbol: '🥴', name: 'Woozy Face', category: 'Smileys & Emotion' },
  { symbol: '😵', name: 'Dizzy Face', category: 'Smileys & Emotion' },
  { symbol: '🤯', name: 'Exploding Head', category: 'Smileys & Emotion' },
  { symbol: '🤠', name: 'Cowboy Hat Face', category: 'Smileys & Emotion' },
  { symbol: '🥳', name: 'Partying Face', category: 'Smileys & Emotion' },
  { symbol: '😎', name: 'Smiling Face with Sunglasses', category: 'Smileys & Emotion' },
  { symbol: '🤓', name: 'Nerd Face', category: 'Smileys & Emotion' },
  { symbol: '🧐', name: 'Face with Monocle', category: 'Smileys & Emotion' },
  { symbol: '😕', name: 'Confused Face', category: 'Smileys & Emotion' },
  { symbol: '😟', name: 'Worried Face', category: 'Smileys & Emotion' },
  { symbol: '🙁', name: 'Slightly Frowning Face', category: 'Smileys & Emotion' },
  { symbol: '☹️', name: 'Frowning Face', category: 'Smileys & Emotion' },
  { symbol: '😮', name: 'Face with Open Mouth', category: 'Smileys & Emotion' },
  { symbol: '😯', name: 'Hushed Face', category: 'Smileys & Emotion' },
  { symbol: '😲', name: 'Astonished Face', category: 'Smileys & Emotion' },
  { symbol: '😳', name: 'Flushed Face', category: 'Smileys & Emotion' },
  { symbol: '🥺', name: 'Pleading Face', category: 'Smileys & Emotion' },
  { symbol: '😦', name: 'Frowning Face with Open Mouth', category: 'Smileys & Emotion' },
  { symbol: '😧', name: 'Anguished Face', category: 'Smileys & Emotion' },
  { symbol: '😨', name: 'Fearful Face', category: 'Smileys & Emotion' },
  { symbol: '😰', name: 'Anxious Face with Sweat', category: 'Smileys & Emotion' },
  { symbol: '😥', name: 'Sad but Relieved Face', category: 'Smileys & Emotion' },
  { symbol: '😢', name: 'Crying Face', category: 'Smileys & Emotion' },
  { symbol: '😭', name: 'Loudly Crying Face', category: 'Smileys & Emotion' },
  { symbol: '😱', name: 'Face Screaming in Fear', category: 'Smileys & Emotion' },
  { symbol: '😖', name: 'Confounded Face', category: 'Smileys & Emotion' },
  { symbol: '😣', name: 'Persevering Face', category: 'Smileys & Emotion' },
  { symbol: '😞', name: 'Disappointed Face', category: 'Smileys & Emotion' },
  { symbol: '😓', name: 'Downcast Face with Sweat', category: 'Smileys & Emotion' },
  { symbol: '😩', name: 'Weary Face', category: 'Smileys & Emotion' },
  { symbol: '😫', name: 'Tired Face', category: 'Smileys & Emotion' },
  { symbol: '🥱', name: 'Yawning Face', category: 'Smileys & Emotion' },
  { symbol: '😤', name: 'Face with Steam From Nose', category: 'Smileys & Emotion' },
  { symbol: '😡', name: 'Pouting Face', category: 'Smileys & Emotion' },
  { symbol: '😠', name: 'Angry Face', category: 'Smileys & Emotion' },
  { symbol: '🤬', name: 'Face with Symbols on Mouth', category: 'Smileys & Emotion' },
  { symbol: '😈', name: 'Smiling Face with Horns', category: 'Smileys & Emotion' },
  { symbol: '👿', name: 'Angry Face with Horns', category: 'Smileys & Emotion' },
  { symbol: '💀', name: 'Skull', category: 'Smileys & Emotion' },
  { symbol: '☠️', name: 'Skull and Crossbones', category: 'Smileys & Emotion' },
  
  // Hearts & Love
  { symbol: '❤️', name: 'Red Heart', category: 'Hearts & Love' },
  { symbol: '🧡', name: 'Orange Heart', category: 'Hearts & Love' },
  { symbol: '💛', name: 'Yellow Heart', category: 'Hearts & Love' },
  { symbol: '💚', name: 'Green Heart', category: 'Hearts & Love' },
  { symbol: '💙', name: 'Blue Heart', category: 'Hearts & Love' },
  { symbol: '💜', name: 'Purple Heart', category: 'Hearts & Love' },
  { symbol: '🖤', name: 'Black Heart', category: 'Hearts & Love' },
  { symbol: '🤍', name: 'White Heart', category: 'Hearts & Love' },
  { symbol: '🤎', name: 'Brown Heart', category: 'Hearts & Love' },
  { symbol: '💔', name: 'Broken Heart', category: 'Hearts & Love' },
  { symbol: '❣️', name: 'Heart Exclamation', category: 'Hearts & Love' },
  { symbol: '💕', name: 'Two Hearts', category: 'Hearts & Love' },
  { symbol: '💞', name: 'Revolving Hearts', category: 'Hearts & Love' },
  { symbol: '💓', name: 'Beating Heart', category: 'Hearts & Love' },
  { symbol: '💗', name: 'Growing Heart', category: 'Hearts & Love' },
  { symbol: '💖', name: 'Sparkling Heart', category: 'Hearts & Love' },
  { symbol: '💘', name: 'Heart with Arrow', category: 'Hearts & Love' },
  { symbol: '💝', name: 'Heart with Ribbon', category: 'Hearts & Love' },
  { symbol: '💟', name: 'Heart Decoration', category: 'Hearts & Love' },
  { symbol: '♥️', name: 'Heart Suit', category: 'Hearts & Love' },
  
  // Animals & Nature
  { symbol: '🐶', name: 'Dog Face', category: 'Animals & Nature' },
  { symbol: '🐱', name: 'Cat Face', category: 'Animals & Nature' },
  { symbol: '🐭', name: 'Mouse Face', category: 'Animals & Nature' },
  { symbol: '🐹', name: 'Hamster Face', category: 'Animals & Nature' },
  { symbol: '🐰', name: 'Rabbit Face', category: 'Animals & Nature' },
  { symbol: '🦊', name: 'Fox Face', category: 'Animals & Nature' },
  { symbol: '🐻', name: 'Bear Face', category: 'Animals & Nature' },
  { symbol: '🐼', name: 'Panda Face', category: 'Animals & Nature' },
  { symbol: '🐨', name: 'Koala', category: 'Animals & Nature' },
  { symbol: '🐯', name: 'Tiger Face', category: 'Animals & Nature' },
  { symbol: '🦁', name: 'Lion Face', category: 'Animals & Nature' },
  { symbol: '🐮', name: 'Cow Face', category: 'Animals & Nature' },
  { symbol: '🐷', name: 'Pig Face', category: 'Animals & Nature' },
  { symbol: '🐽', name: 'Pig Nose', category: 'Animals & Nature' },
  { symbol: '🐸', name: 'Frog Face', category: 'Animals & Nature' },
  { symbol: '🐵', name: 'Monkey Face', category: 'Animals & Nature' },
  { symbol: '🙈', name: 'See-No-Evil Monkey', category: 'Animals & Nature' },
  { symbol: '🙉', name: 'Hear-No-Evil Monkey', category: 'Animals & Nature' },
  { symbol: '🙊', name: 'Speak-No-Evil Monkey', category: 'Animals & Nature' },
  { symbol: '🐒', name: 'Monkey', category: 'Animals & Nature' },
  { symbol: '🐔', name: 'Chicken', category: 'Animals & Nature' },
  { symbol: '🐧', name: 'Penguin', category: 'Animals & Nature' },
  { symbol: '🐦', name: 'Bird', category: 'Animals & Nature' },
  { symbol: '🐤', name: 'Baby Chick', category: 'Animals & Nature' },
  { symbol: '🐣', name: 'Hatching Chick', category: 'Animals & Nature' },
  { symbol: '🐥', name: 'Front-Facing Baby Chick', category: 'Animals & Nature' },
  { symbol: '🦆', name: 'Duck', category: 'Animals & Nature' },
  { symbol: '🦅', name: 'Eagle', category: 'Animals & Nature' },
  { symbol: '🦉', name: 'Owl', category: 'Animals & Nature' },
  { symbol: '🦇', name: 'Bat', category: 'Animals & Nature' },
  { symbol: '🐺', name: 'Wolf Face', category: 'Animals & Nature' },
  { symbol: '🐗', name: 'Boar', category: 'Animals & Nature' },
  { symbol: '🐴', name: 'Horse Face', category: 'Animals & Nature' },
  { symbol: '🦄', name: 'Unicorn Face', category: 'Animals & Nature' },
  { symbol: '🐝', name: 'Honeybee', category: 'Animals & Nature' },
  { symbol: '🐛', name: 'Bug', category: 'Animals & Nature' },
  { symbol: '🦋', name: 'Butterfly', category: 'Animals & Nature' },
  { symbol: '🐌', name: 'Snail', category: 'Animals & Nature' },
  { symbol: '🐞', name: 'Lady Beetle', category: 'Animals & Nature' },
  { symbol: '🐜', name: 'Ant', category: 'Animals & Nature' },
  { symbol: '🦟', name: 'Mosquito', category: 'Animals & Nature' },
  { symbol: '🦗', name: 'Cricket', category: 'Animals & Nature' },
  { symbol: '🕷️', name: 'Spider', category: 'Animals & Nature' },
  { symbol: '🕸️', name: 'Spider Web', category: 'Animals & Nature' },
  { symbol: '🦂', name: 'Scorpion', category: 'Animals & Nature' },
  { symbol: '🐢', name: 'Turtle', category: 'Animals & Nature' },
  { symbol: '🐍', name: 'Snake', category: 'Animals & Nature' },
  { symbol: '🦎', name: 'Lizard', category: 'Animals & Nature' },
  { symbol: '🦖', name: 'T-Rex', category: 'Animals & Nature' },
  { symbol: '🦕', name: 'Sauropod', category: 'Animals & Nature' },
  { symbol: '🐙', name: 'Octopus', category: 'Animals & Nature' },
  { symbol: '🦑', name: 'Squid', category: 'Animals & Nature' },
  { symbol: '🦐', name: 'Shrimp', category: 'Animals & Nature' },
  { symbol: '🦞', name: 'Lobster', category: 'Animals & Nature' },
  { symbol: '🦀', name: 'Crab', category: 'Animals & Nature' },
  { symbol: '🐡', name: 'Blowfish', category: 'Animals & Nature' },
  { symbol: '🐠', name: 'Tropical Fish', category: 'Animals & Nature' },
  { symbol: '🐟', name: 'Fish', category: 'Animals & Nature' },
  { symbol: '🐬', name: 'Dolphin', category: 'Animals & Nature' },
  { symbol: '🐳', name: 'Spouting Whale', category: 'Animals & Nature' },
  { symbol: '🐋', name: 'Whale', category: 'Animals & Nature' },
  { symbol: '🦈', name: 'Shark', category: 'Animals & Nature' },
  
  // Food & Drink
  { symbol: '🍎', name: 'Red Apple', category: 'Food & Drink' },
  { symbol: '🍏', name: 'Green Apple', category: 'Food & Drink' },
  { symbol: '🍊', name: 'Tangerine', category: 'Food & Drink' },
  { symbol: '🍋', name: 'Lemon', category: 'Food & Drink' },
  { symbol: '🍌', name: 'Banana', category: 'Food & Drink' },
  { symbol: '🍉', name: 'Watermelon', category: 'Food & Drink' },
  { symbol: '🍇', name: 'Grapes', category: 'Food & Drink' },
  { symbol: '🍓', name: 'Strawberry', category: 'Food & Drink' },
  { symbol: '🍈', name: 'Melon', category: 'Food & Drink' },
  { symbol: '🍒', name: 'Cherries', category: 'Food & Drink' },
  { symbol: '🍑', name: 'Peach', category: 'Food & Drink' },
  { symbol: '🥭', name: 'Mango', category: 'Food & Drink' },
  { symbol: '🍍', name: 'Pineapple', category: 'Food & Drink' },
  { symbol: '🥥', name: 'Coconut', category: 'Food & Drink' },
  { symbol: '🥝', name: 'Kiwi Fruit', category: 'Food & Drink' },
  { symbol: '🍅', name: 'Tomato', category: 'Food & Drink' },
  { symbol: '🍆', name: 'Eggplant', category: 'Food & Drink' },
  { symbol: '🥑', name: 'Avocado', category: 'Food & Drink' },
  { symbol: '🥦', name: 'Broccoli', category: 'Food & Drink' },
  { symbol: '🥬', name: 'Leafy Greens', category: 'Food & Drink' },
  { symbol: '🥒', name: 'Cucumber', category: 'Food & Drink' },
  { symbol: '🌶️', name: 'Hot Pepper', category: 'Food & Drink' },
  { symbol: '🌽', name: 'Ear of Corn', category: 'Food & Drink' },
  { symbol: '🥕', name: 'Carrot', category: 'Food & Drink' },
  { symbol: '🧄', name: 'Garlic', category: 'Food & Drink' },
  { symbol: '🧅', name: 'Onion', category: 'Food & Drink' },
  { symbol: '🥔', name: 'Potato', category: 'Food & Drink' },
  { symbol: '🍠', name: 'Roasted Sweet Potato', category: 'Food & Drink' },
  { symbol: '🥐', name: 'Croissant', category: 'Food & Drink' },
  { symbol: '🥖', name: 'Baguette Bread', category: 'Food & Drink' },
  { symbol: '🍞', name: 'Bread', category: 'Food & Drink' },
  { symbol: '🥨', name: 'Pretzel', category: 'Food & Drink' },
  { symbol: '🥯', name: 'Bagel', category: 'Food & Drink' },
  { symbol: '🥞', name: 'Pancakes', category: 'Food & Drink' },
  { symbol: '🧇', name: 'Waffle', category: 'Food & Drink' },
  { symbol: '🧀', name: 'Cheese Wedge', category: 'Food & Drink' },
  { symbol: '🍖', name: 'Meat on Bone', category: 'Food & Drink' },
  { symbol: '🍗', name: 'Poultry Leg', category: 'Food & Drink' },
  { symbol: '🥩', name: 'Cut of Meat', category: 'Food & Drink' },
  { symbol: '🥓', name: 'Bacon', category: 'Food & Drink' },
  { symbol: '🍔', name: 'Hamburger', category: 'Food & Drink' },
  { symbol: '🍟', name: 'French Fries', category: 'Food & Drink' },
  { symbol: '🍕', name: 'Pizza', category: 'Food & Drink' },
  { symbol: '🌭', name: 'Hot Dog', category: 'Food & Drink' },
  { symbol: '🥪', name: 'Sandwich', category: 'Food & Drink' },
  { symbol: '🌮', name: 'Taco', category: 'Food & Drink' },
  { symbol: '🌯', name: 'Burrito', category: 'Food & Drink' },
  { symbol: '🥙', name: 'Stuffed Flatbread', category: 'Food & Drink' },
  { symbol: '🧆', name: 'Falafel', category: 'Food & Drink' },
  { symbol: '🥚', name: 'Egg', category: 'Food & Drink' },
  { symbol: '🍳', name: 'Cooking', category: 'Food & Drink' },
  { symbol: '🥘', name: 'Shallow Pan of Food', category: 'Food & Drink' },
  { symbol: '🍲', name: 'Pot of Food', category: 'Food & Drink' },
  { symbol: '🥣', name: 'Bowl with Spoon', category: 'Food & Drink' },
  { symbol: '🥗', name: 'Green Salad', category: 'Food & Drink' },
  { symbol: '🍿', name: 'Popcorn', category: 'Food & Drink' },
  { symbol: '🧈', name: 'Butter', category: 'Food & Drink' },
  { symbol: '🧂', name: 'Salt', category: 'Food & Drink' },
  { symbol: '🥫', name: 'Canned Food', category: 'Food & Drink' },
  { symbol: '🍱', name: 'Bento Box', category: 'Food & Drink' },
  { symbol: '🍘', name: 'Rice Cracker', category: 'Food & Drink' },
  { symbol: '🍙', name: 'Rice Ball', category: 'Food & Drink' },
  { symbol: '🍚', name: 'Cooked Rice', category: 'Food & Drink' },
  { symbol: '🍛', name: 'Curry Rice', category: 'Food & Drink' },
  { symbol: '🍜', name: 'Steaming Bowl', category: 'Food & Drink' },
  { symbol: '🍝', name: 'Spaghetti', category: 'Food & Drink' },
  { symbol: '🍠', name: 'Roasted Sweet Potato', category: 'Food & Drink' },
  { symbol: '🍢', name: 'Oden', category: 'Food & Drink' },
  { symbol: '🍣', name: 'Sushi', category: 'Food & Drink' },
  { symbol: '🍤', name: 'Fried Shrimp', category: 'Food & Drink' },
  { symbol: '🍥', name: 'Fish Cake with Swirl', category: 'Food & Drink' },
  { symbol: '🥮', name: 'Moon Cake', category: 'Food & Drink' },
  { symbol: '🍡', name: 'Dango', category: 'Food & Drink' },
  { symbol: '🥟', name: 'Dumpling', category: 'Food & Drink' },
  { symbol: '🥠', name: 'Fortune Cookie', category: 'Food & Drink' },
  { symbol: '🥡', name: 'Takeout Box', category: 'Food & Drink' },
  { symbol: '🍦', name: 'Soft Ice Cream', category: 'Food & Drink' },
  { symbol: '🍧', name: 'Shaved Ice', category: 'Food & Drink' },
  { symbol: '🍨', name: 'Ice Cream', category: 'Food & Drink' },
  { symbol: '🍩', name: 'Doughnut', category: 'Food & Drink' },
  { symbol: '🍪', name: 'Cookie', category: 'Food & Drink' },
  { symbol: '🎂', name: 'Birthday Cake', category: 'Food & Drink' },
  { symbol: '🍰', name: 'Shortcake', category: 'Food & Drink' },
  { symbol: '🧁', name: 'Cupcake', category: 'Food & Drink' },
  { symbol: '🥧', name: 'Pie', category: 'Food & Drink' },
  { symbol: '🍫', name: 'Chocolate Bar', category: 'Food & Drink' },
  { symbol: '🍬', name: 'Candy', category: 'Food & Drink' },
  { symbol: '🍭', name: 'Lollipop', category: 'Food & Drink' },
  { symbol: '🍮', name: 'Custard', category: 'Food & Drink' },
  { symbol: '🍯', name: 'Honey Pot', category: 'Food & Drink' },
  { symbol: '🍼', name: 'Baby Bottle', category: 'Food & Drink' },
  { symbol: '🥛', name: 'Glass of Milk', category: 'Food & Drink' },
  { symbol: '☕', name: 'Hot Beverage', category: 'Food & Drink' },
  { symbol: '🍵', name: 'Teacup Without Handle', category: 'Food & Drink' },
  { symbol: '🍶', name: 'Sake', category: 'Food & Drink' },
  { symbol: '🍾', name: 'Bottle with Popping Cork', category: 'Food & Drink' },
  { symbol: '🍷', name: 'Wine Glass', category: 'Food & Drink' },
  { symbol: '🍸', name: 'Cocktail Glass', category: 'Food & Drink' },
  { symbol: '🍹', name: 'Tropical Drink', category: 'Food & Drink' },
  { symbol: '🍺', name: 'Beer Mug', category: 'Food & Drink' },
  { symbol: '🍻', name: 'Clinking Beer Mugs', category: 'Food & Drink' },
  { symbol: '🥂', name: 'Clinking Glasses', category: 'Food & Drink' },
  { symbol: '🥃', name: 'Tumbler Glass', category: 'Food & Drink' },
  { symbol: '🥤', name: 'Cup with Straw', category: 'Food & Drink' },
  { symbol: '🧃', name: 'Beverage Box', category: 'Food & Drink' },
  { symbol: '🧉', name: 'Mate', category: 'Food & Drink' },
  { symbol: '🧊', name: 'Ice Cube', category: 'Food & Drink' },
  
  // Activities & Sports
  { symbol: '⚽', name: 'Soccer Ball', category: 'Activities & Sports' },
  { symbol: '🏀', name: 'Basketball', category: 'Activities & Sports' },
  { symbol: '🏈', name: 'American Football', category: 'Activities & Sports' },
  { symbol: '⚾', name: 'Baseball', category: 'Activities & Sports' },
  { symbol: '🥎', name: 'Softball', category: 'Activities & Sports' },
  { symbol: '🎾', name: 'Tennis', category: 'Activities & Sports' },
  { symbol: '🏐', name: 'Volleyball', category: 'Activities & Sports' },
  { symbol: '🏉', name: 'Rugby Football', category: 'Activities & Sports' },
  { symbol: '🥏', name: 'Flying Disc', category: 'Activities & Sports' },
  { symbol: '🎱', name: 'Pool 8 Ball', category: 'Activities & Sports' },
  { symbol: '🪀', name: 'Yo-Yo', category: 'Activities & Sports' },
  { symbol: '🏓', name: 'Ping Pong', category: 'Activities & Sports' },
  { symbol: '🏸', name: 'Badminton', category: 'Activities & Sports' },
  { symbol: '🏒', name: 'Ice Hockey', category: 'Activities & Sports' },
  { symbol: '🏑', name: 'Field Hockey', category: 'Activities & Sports' },
  { symbol: '🥍', name: 'Lacrosse', category: 'Activities & Sports' },
  { symbol: '🏏', name: 'Cricket Game', category: 'Activities & Sports' },
  { symbol: '🥅', name: 'Goal Net', category: 'Activities & Sports' },
  { symbol: '⛳', name: 'Flag in Hole', category: 'Activities & Sports' },
  { symbol: '🪁', name: 'Kite', category: 'Activities & Sports' },
  { symbol: '🏹', name: 'Bow and Arrow', category: 'Activities & Sports' },
  { symbol: '🎣', name: 'Fishing Pole', category: 'Activities & Sports' },
  { symbol: '🤿', name: 'Diving Mask', category: 'Activities & Sports' },
  { symbol: '🥊', name: 'Boxing Glove', category: 'Activities & Sports' },
  { symbol: '🥋', name: 'Martial Arts Uniform', category: 'Activities & Sports' },
  { symbol: '🎽', name: 'Running Shirt', category: 'Activities & Sports' },
  { symbol: '🛹', name: 'Skateboard', category: 'Activities & Sports' },
  { symbol: '🛷', name: 'Sled', category: 'Activities & Sports' },
  { symbol: '⛸️', name: 'Ice Skate', category: 'Activities & Sports' },
  { symbol: '🥌', name: 'Curling Stone', category: 'Activities & Sports' },
  { symbol: '🎿', name: 'Skis', category: 'Activities & Sports' },
  { symbol: '⛷️', name: 'Skier', category: 'Activities & Sports' },
  { symbol: '🏂', name: 'Snowboarder', category: 'Activities & Sports' },
  { symbol: '🪂', name: 'Parachute', category: 'Activities & Sports' },
  { symbol: '🏋️‍♀️', name: 'Woman Lifting Weights', category: 'Activities & Sports' },
  { symbol: '🏋️‍♂️', name: 'Man Lifting Weights', category: 'Activities & Sports' },
  { symbol: '🤼‍♀️', name: 'Women Wrestling', category: 'Activities & Sports' },
  { symbol: '🤼‍♂️', name: 'Men Wrestling', category: 'Activities & Sports' },
  { symbol: '🤸‍♀️', name: 'Woman Cartwheeling', category: 'Activities & Sports' },
  { symbol: '🤸‍♂️', name: 'Man Cartwheeling', category: 'Activities & Sports' },
  { symbol: '⛹️‍♀️', name: 'Woman Bouncing Ball', category: 'Activities & Sports' },
  { symbol: '⛹️‍♂️', name: 'Man Bouncing Ball', category: 'Activities & Sports' },
  { symbol: '🤺', name: 'Person Fencing', category: 'Activities & Sports' },
  { symbol: '🤾‍♀️', name: 'Woman Playing Handball', category: 'Activities & Sports' },
  { symbol: '🤾‍♂️', name: 'Man Playing Handball', category: 'Activities & Sports' },
  { symbol: '🏌️‍♀️', name: 'Woman Golfing', category: 'Activities & Sports' },
  { symbol: '🏌️‍♂️', name: 'Man Golfing', category: 'Activities & Sports' },
  { symbol: '🏇', name: 'Horse Racing', category: 'Activities & Sports' },
  { symbol: '🧘‍♀️', name: 'Woman in Lotus Position', category: 'Activities & Sports' },
  { symbol: '🧘‍♂️', name: 'Man in Lotus Position', category: 'Activities & Sports' },
  { symbol: '🏄‍♀️', name: 'Woman Surfing', category: 'Activities & Sports' },
  { symbol: '🏄‍♂️', name: 'Man Surfing', category: 'Activities & Sports' },
  { symbol: '🏊‍♀️', name: 'Woman Swimming', category: 'Activities & Sports' },
  { symbol: '🏊‍♂️', name: 'Man Swimming', category: 'Activities & Sports' },
  { symbol: '🤽‍♀️', name: 'Woman Playing Water Polo', category: 'Activities & Sports' },
  { symbol: '🤽‍♂️', name: 'Man Playing Water Polo', category: 'Activities & Sports' },
  { symbol: '🚣‍♀️', name: 'Woman Rowing Boat', category: 'Activities & Sports' },
  { symbol: '🚣‍♂️', name: 'Man Rowing Boat', category: 'Activities & Sports' },
  { symbol: '🧗‍♀️', name: 'Woman Climbing', category: 'Activities & Sports' },
  { symbol: '🧗‍♂️', name: 'Man Climbing', category: 'Activities & Sports' },
  { symbol: '🚵‍♀️', name: 'Woman Mountain Biking', category: 'Activities & Sports' },
  { symbol: '🚵‍♂️', name: 'Man Mountain Biking', category: 'Activities & Sports' },
  { symbol: '🚴‍♀️', name: 'Woman Biking', category: 'Activities & Sports' },
  { symbol: '🚴‍♂️', name: 'Man Biking', category: 'Activities & Sports' },
  { symbol: '🏆', name: 'Trophy', category: 'Activities & Sports' },
  { symbol: '🥇', name: 'First Place Medal', category: 'Activities & Sports' },
  { symbol: '🥈', name: 'Second Place Medal', category: 'Activities & Sports' },
  { symbol: '🥉', name: 'Third Place Medal', category: 'Activities & Sports' },
  { symbol: '🏅', name: 'Sports Medal', category: 'Activities & Sports' },
  { symbol: '🎖️', name: 'Military Medal', category: 'Activities & Sports' },
  { symbol: '🏵️', name: 'Rosette', category: 'Activities & Sports' },
  { symbol: '🎗️', name: 'Reminder Ribbon', category: 'Activities & Sports' },
  { symbol: '🎫', name: 'Ticket', category: 'Activities & Sports' },
  { symbol: '🎟️', name: 'Admission Tickets', category: 'Activities & Sports' },
  { symbol: '🎪', name: 'Circus Tent', category: 'Activities & Sports' },
  { symbol: '🤹‍♀️', name: 'Woman Juggling', category: 'Activities & Sports' },
  { symbol: '🤹‍♂️', name: 'Man Juggling', category: 'Activities & Sports' },
  { symbol: '🎭', name: 'Performing Arts', category: 'Activities & Sports' },
  { symbol: '🩰', name: 'Ballet Shoes', category: 'Activities & Sports' },
  { symbol: '🎨', name: 'Artist Palette', category: 'Activities & Sports' },
  { symbol: '🎬', name: 'Clapper Board', category: 'Activities & Sports' },
  { symbol: '🎤', name: 'Microphone', category: 'Activities & Sports' },
  { symbol: '🎧', name: 'Headphone', category: 'Activities & Sports' },
  { symbol: '🎼', name: 'Musical Score', category: 'Activities & Sports' },
  { symbol: '🎵', name: 'Musical Note', category: 'Activities & Sports' },
  { symbol: '🎶', name: 'Musical Notes', category: 'Activities & Sports' },
  { symbol: '🎹', name: 'Musical Keyboard', category: 'Activities & Sports' },
  { symbol: '🥁', name: 'Drum', category: 'Activities & Sports' },
  { symbol: '🎷', name: 'Saxophone', category: 'Activities & Sports' },
  { symbol: '🎺', name: 'Trumpet', category: 'Activities & Sports' },
  { symbol: '🎸', name: 'Guitar', category: 'Activities & Sports' },
  { symbol: '🪕', name: 'Banjo', category: 'Activities & Sports' },
  { symbol: '🎻', name: 'Violin', category: 'Activities & Sports' },
  { symbol: '🎲', name: 'Game Die', category: 'Activities & Sports' },
  { symbol: '♟️', name: 'Chess Pawn', category: 'Activities & Sports' },
  { symbol: '🎯', name: 'Direct Hit', category: 'Activities & Sports' },
  { symbol: '🎳', name: 'Bowling', category: 'Activities & Sports' },
  { symbol: '🎮', name: 'Video Game', category: 'Activities & Sports' },
  { symbol: '🎰', name: 'Slot Machine', category: 'Activities & Sports' },
  { symbol: '🧩', name: 'Puzzle Piece', category: 'Activities & Sports' },
  
  // Travel & Places
  { symbol: '🚗', name: 'Automobile', category: 'Travel & Places' },
  { symbol: '🚕', name: 'Taxi', category: 'Travel & Places' },
  { symbol: '🚙', name: 'Sport Utility Vehicle', category: 'Travel & Places' },
  { symbol: '🚌', name: 'Bus', category: 'Travel & Places' },
  { symbol: '🚎', name: 'Trolleybus', category: 'Travel & Places' },
  { symbol: '🏎️', name: 'Racing Car', category: 'Travel & Places' },
  { symbol: '🚓', name: 'Police Car', category: 'Travel & Places' },
  { symbol: '🚑', name: 'Ambulance', category: 'Travel & Places' },
  { symbol: '🚒', name: 'Fire Engine', category: 'Travel & Places' },
  { symbol: '🚐', name: 'Minibus', category: 'Travel & Places' },
  { symbol: '🛻', name: 'Pickup Truck', category: 'Travel & Places' },
  { symbol: '🚚', name: 'Delivery Truck', category: 'Travel & Places' },
  { symbol: '🚛', name: 'Articulated Lorry', category: 'Travel & Places' },
  { symbol: '🚜', name: 'Tractor', category: 'Travel & Places' },
  { symbol: '🏍️', name: 'Motorcycle', category: 'Travel & Places' },
  { symbol: '🛵', name: 'Motor Scooter', category: 'Travel & Places' },
  { symbol: '🚲', name: 'Bicycle', category: 'Travel & Places' },
  { symbol: '🛴', name: 'Kick Scooter', category: 'Travel & Places' },
  { symbol: '🛼', name: 'Roller Skate', category: 'Travel & Places' },
  { symbol: '🚁', name: 'Helicopter', category: 'Travel & Places' },
  { symbol: '🛸', name: 'Flying Saucer', category: 'Travel & Places' },
  { symbol: '✈️', name: 'Airplane', category: 'Travel & Places' },
  { symbol: '🛩️', name: 'Small Airplane', category: 'Travel & Places' },
  { symbol: '🛫', name: 'Airplane Departure', category: 'Travel & Places' },
  { symbol: '🛬', name: 'Airplane Arrival', category: 'Travel & Places' },
  { symbol: '🪂', name: 'Parachute', category: 'Travel & Places' },
  { symbol: '💺', name: 'Seat', category: 'Travel & Places' },
  { symbol: '🚀', name: 'Rocket', category: 'Travel & Places' },
  { symbol: '🛰️', name: 'Satellite', category: 'Travel & Places' },
  { symbol: '🚉', name: 'Station', category: 'Travel & Places' },
  { symbol: '🚞', name: 'Mountain Railway', category: 'Travel & Places' },
  { symbol: '🚝', name: 'Monorail', category: 'Travel & Places' },
  { symbol: '🚄', name: 'High-Speed Train', category: 'Travel & Places' },
  { symbol: '🚅', name: 'Bullet Train', category: 'Travel & Places' },
  { symbol: '🚈', name: 'Light Rail', category: 'Travel & Places' },
  { symbol: '🚂', name: 'Locomotive', category: 'Travel & Places' },
  { symbol: '🚆', name: 'Train', category: 'Travel & Places' },
  { symbol: '🚇', name: 'Metro', category: 'Travel & Places' },
  { symbol: '🚊', name: 'Tram', category: 'Travel & Places' },
  { symbol: '🚃', name: 'Railway Car', category: 'Travel & Places' },
  { symbol: '🚋', name: 'Tram Car', category: 'Travel & Places' },
  { symbol: '🚍', name: 'Oncoming Bus', category: 'Travel & Places' },
  { symbol: '🚘', name: 'Oncoming Automobile', category: 'Travel & Places' },
  { symbol: '🚖', name: 'Oncoming Taxi', category: 'Travel & Places' },
  { symbol: '🚡', name: 'Aerial Tramway', category: 'Travel & Places' },
  { symbol: '🚠', name: 'Mountain Cableway', category: 'Travel & Places' },
  { symbol: '🚟', name: 'Suspension Railway', category: 'Travel & Places' },
  { symbol: '🎢', name: 'Roller Coaster', category: 'Travel & Places' },
  { symbol: '🎡', name: 'Ferris Wheel', category: 'Travel & Places' },
  { symbol: '🎠', name: 'Carousel Horse', category: 'Travel & Places' },
  { symbol: '🏗️', name: 'Building Construction', category: 'Travel & Places' },
  { symbol: '🌁', name: 'Foggy', category: 'Travel & Places' },
  { symbol: '🗼', name: 'Tokyo Tower', category: 'Travel & Places' },
  { symbol: '🗽', name: 'Statue of Liberty', category: 'Travel & Places' },
  { symbol: '⛪', name: 'Church', category: 'Travel & Places' },
  { symbol: '🕌', name: 'Mosque', category: 'Travel & Places' },
  { symbol: '🛕', name: 'Hindu Temple', category: 'Travel & Places' },
  { symbol: '🕍', name: 'Synagogue', category: 'Travel & Places' },
  { symbol: '⛩️', name: 'Shinto Shrine', category: 'Travel & Places' },
  { symbol: '🕋', name: 'Kaaba', category: 'Travel & Places' },
  { symbol: '⛲', name: 'Fountain', category: 'Travel & Places' },
  { symbol: '⛺', name: 'Tent', category: 'Travel & Places' },
  { symbol: '🌁', name: 'Foggy', category: 'Travel & Places' },
  { symbol: '🌃', name: 'Night with Stars', category: 'Travel & Places' },
  { symbol: '🏙️', name: 'Cityscape', category: 'Travel & Places' },
  { symbol: '🌄', name: 'Sunrise Over Mountains', category: 'Travel & Places' },
  { symbol: '🌅', name: 'Sunrise', category: 'Travel & Places' },
  { symbol: '🌆', name: 'Cityscape at Dusk', category: 'Travel & Places' },
  { symbol: '🌇', name: 'Sunset', category: 'Travel & Places' },
  { symbol: '🌉', name: 'Bridge at Night', category: 'Travel & Places' },
  { symbol: '♨️', name: 'Hot Springs', category: 'Travel & Places' },
  { symbol: '🎆', name: 'Fireworks', category: 'Travel & Places' },
  { symbol: '🎇', name: 'Sparkler', category: 'Travel & Places' },
  { symbol: '🌠', name: 'Shooting Star', category: 'Travel & Places' },
  { symbol: '🎑', name: 'Moon Viewing Ceremony', category: 'Travel & Places' },
  { symbol: '🏞️', name: 'National Park', category: 'Travel & Places' },
  { symbol: '🏟️', name: 'Stadium', category: 'Travel & Places' },
  { symbol: '🏛️', name: 'Classical Building', category: 'Travel & Places' },
  { symbol: '🏗️', name: 'Building Construction', category: 'Travel & Places' },
  { symbol: '🧱', name: 'Brick', category: 'Travel & Places' },
  { symbol: '🏘️', name: 'Houses', category: 'Travel & Places' },
  { symbol: '🏚️', name: 'Derelict House', category: 'Travel & Places' },
  { symbol: '🏠', name: 'House', category: 'Travel & Places' },
  { symbol: '🏡', name: 'House with Garden', category: 'Travel & Places' },
  { symbol: '🏢', name: 'Office Building', category: 'Travel & Places' },
  { symbol: '🏣', name: 'Japanese Post Office', category: 'Travel & Places' },
  { symbol: '🏤', name: 'Post Office', category: 'Travel & Places' },
  { symbol: '🏥', name: 'Hospital', category: 'Travel & Places' },
  { symbol: '🏦', name: 'Bank', category: 'Travel & Places' },
  { symbol: '🏨', name: 'Hotel', category: 'Travel & Places' },
  { symbol: '🏩', name: 'Love Hotel', category: 'Travel & Places' },
  { symbol: '🏪', name: 'Convenience Store', category: 'Travel & Places' },
  { symbol: '🏫', name: 'School', category: 'Travel & Places' },
  { symbol: '🏬', name: 'Department Store', category: 'Travel & Places' },
  { symbol: '🏭', name: 'Factory', category: 'Travel & Places' },
  { symbol: '🏯', name: 'Japanese Castle', category: 'Travel & Places' },
  { symbol: '🏰', name: 'Castle', category: 'Travel & Places' },
  { symbol: '💒', name: 'Wedding', category: 'Travel & Places' },
  { symbol: '🗾', name: 'Map of Japan', category: 'Travel & Places' },
  { symbol: '🗺️', name: 'World Map', category: 'Travel & Places' },
  { symbol: '🌍', name: 'Globe Showing Europe-Africa', category: 'Travel & Places' },
  { symbol: '🌎', name: 'Globe Showing Americas', category: 'Travel & Places' },
  { symbol: '🌏', name: 'Globe Showing Asia-Australia', category: 'Travel & Places' },
  { symbol: '🌐', name: 'Globe with Meridians', category: 'Travel & Places' },
  { symbol: '🗻', name: 'Mount Fuji', category: 'Travel & Places' },
  { symbol: '🌋', name: 'Volcano', category: 'Travel & Places' },
  { symbol: '⛰️', name: 'Mountain', category: 'Travel & Places' },
  { symbol: '🏔️', name: 'Snow-Capped Mountain', category: 'Travel & Places' },
  { symbol: '🗻', name: 'Mount Fuji', category: 'Travel & Places' },
  { symbol: '🏕️', name: 'Camping', category: 'Travel & Places' },
  { symbol: '🏖️', name: 'Beach with Umbrella', category: 'Travel & Places' },
  { symbol: '🏜️', name: 'Desert', category: 'Travel & Places' },
  { symbol: '🏝️', name: 'Desert Island', category: 'Travel & Places' },
  
  // Objects & Symbols
  { symbol: '⌚', name: 'Watch', category: 'Objects & Symbols' },
  { symbol: '📱', name: 'Mobile Phone', category: 'Objects & Symbols' },
  { symbol: '📲', name: 'Mobile Phone with Arrow', category: 'Objects & Symbols' },
  { symbol: '💻', name: 'Laptop Computer', category: 'Objects & Symbols' },
  { symbol: '⌨️', name: 'Keyboard', category: 'Objects & Symbols' },
  { symbol: '🖥️', name: 'Desktop Computer', category: 'Objects & Symbols' },
  { symbol: '🖨️', name: 'Printer', category: 'Objects & Symbols' },
  { symbol: '🖱️', name: 'Computer Mouse', category: 'Objects & Symbols' },
  { symbol: '🖲️', name: 'Trackball', category: 'Objects & Symbols' },
  { symbol: '🕹️', name: 'Joystick', category: 'Objects & Symbols' },
  { symbol: '🗜️', name: 'Clamp', category: 'Objects & Symbols' },
  { symbol: '💽', name: 'Computer Disk', category: 'Objects & Symbols' },
  { symbol: '💾', name: 'Floppy Disk', category: 'Objects & Symbols' },
  { symbol: '💿', name: 'Optical Disk', category: 'Objects & Symbols' },
  { symbol: '📀', name: 'DVD', category: 'Objects & Symbols' },
  { symbol: '🧮', name: 'Abacus', category: 'Objects & Symbols' },
  { symbol: '🎥', name: 'Movie Camera', category: 'Objects & Symbols' },
  { symbol: '🎞️', name: 'Film Frames', category: 'Objects & Symbols' },
  { symbol: '📽️', name: 'Film Projector', category: 'Objects & Symbols' },
  { symbol: '🎬', name: 'Clapper Board', category: 'Objects & Symbols' },
  { symbol: '📺', name: 'Television', category: 'Objects & Symbols' },
  { symbol: '📷', name: 'Camera', category: 'Objects & Symbols' },
  { symbol: '📸', name: 'Camera with Flash', category: 'Objects & Symbols' },
  { symbol: '📹', name: 'Video Camera', category: 'Objects & Symbols' },
  { symbol: '📼', name: 'Videocassette', category: 'Objects & Symbols' },
  { symbol: '🔍', name: 'Magnifying Glass Tilted Left', category: 'Objects & Symbols' },
  { symbol: '🔎', name: 'Magnifying Glass Tilted Right', category: 'Objects & Symbols' },
  { symbol: '🕯️', name: 'Candle', category: 'Objects & Symbols' },
  { symbol: '💡', name: 'Light Bulb', category: 'Objects & Symbols' },
  { symbol: '🔦', name: 'Flashlight', category: 'Objects & Symbols' },
  { symbol: '🏮', name: 'Red Paper Lantern', category: 'Objects & Symbols' },
  { symbol: '🪔', name: 'Diya Lamp', category: 'Objects & Symbols' },
  { symbol: '📔', name: 'Notebook with Decorative Cover', category: 'Objects & Symbols' },
  { symbol: '📕', name: 'Closed Book', category: 'Objects & Symbols' },
  { symbol: '📖', name: 'Open Book', category: 'Objects & Symbols' },
  { symbol: '📗', name: 'Green Book', category: 'Objects & Symbols' },
  { symbol: '📘', name: 'Blue Book', category: 'Objects & Symbols' },
  { symbol: '📙', name: 'Orange Book', category: 'Objects & Symbols' },
  { symbol: '📚', name: 'Books', category: 'Objects & Symbols' },
  { symbol: '📓', name: 'Notebook', category: 'Objects & Symbols' },
  { symbol: '📒', name: 'Ledger', category: 'Objects & Symbols' },
  { symbol: '📃', name: 'Page with Curl', category: 'Objects & Symbols' },
  { symbol: '📜', name: 'Scroll', category: 'Objects & Symbols' },
  { symbol: '📄', name: 'Page Facing Up', category: 'Objects & Symbols' },
  { symbol: '📰', name: 'Newspaper', category: 'Objects & Symbols' },
  { symbol: '🗞️', name: 'Rolled-Up Newspaper', category: 'Objects & Symbols' },
  { symbol: '📑', name: 'Bookmark Tabs', category: 'Objects & Symbols' },
  { symbol: '🔖', name: 'Bookmark', category: 'Objects & Symbols' },
  { symbol: '🏷️', name: 'Label', category: 'Objects & Symbols' },
  { symbol: '💰', name: 'Money Bag', category: 'Objects & Symbols' },
  { symbol: '🪙', name: 'Coin', category: 'Objects & Symbols' },
  { symbol: '💴', name: 'Yen Banknote', category: 'Objects & Symbols' },
  { symbol: '💵', name: 'Dollar Banknote', category: 'Objects & Symbols' },
  { symbol: '💶', name: 'Euro Banknote', category: 'Objects & Symbols' },
  { symbol: '💷', name: 'Pound Banknote', category: 'Objects & Symbols' },
  { symbol: '💸', name: 'Money with Wings', category: 'Objects & Symbols' },
  { symbol: '💳', name: 'Credit Card', category: 'Objects & Symbols' },
  { symbol: '🧾', name: 'Receipt', category: 'Objects & Symbols' },
  { symbol: '💎', name: 'Gem Stone', category: 'Objects & Symbols' },
  { symbol: '⚖️', name: 'Balance Scale', category: 'Objects & Symbols' },
  { symbol: '🧰', name: 'Toolbox', category: 'Objects & Symbols' },
  { symbol: '🔧', name: 'Wrench', category: 'Objects & Symbols' },
  { symbol: '🔨', name: 'Hammer', category: 'Objects & Symbols' },
  { symbol: '⚒️', name: 'Hammer and Pick', category: 'Objects & Symbols' },
  { symbol: '🛠️', name: 'Hammer and Wrench', category: 'Objects & Symbols' },
  { symbol: '⛏️', name: 'Pick', category: 'Objects & Symbols' },
  { symbol: '🔩', name: 'Nut and Bolt', category: 'Objects & Symbols' },
  { symbol: '⚙️', name: 'Gear', category: 'Objects & Symbols' },
  { symbol: '🧱', name: 'Brick', category: 'Objects & Symbols' },
  { symbol: '⛓️', name: 'Chains', category: 'Objects & Symbols' },
  { symbol: '🧲', name: 'Magnet', category: 'Objects & Symbols' },
  { symbol: '🔫', name: 'Pistol', category: 'Objects & Symbols' },
  { symbol: '💣', name: 'Bomb', category: 'Objects & Symbols' },
  { symbol: '🧨', name: 'Firecracker', category: 'Objects & Symbols' },
  { symbol: '🪓', name: 'Axe', category: 'Objects & Symbols' },
  { symbol: '🔪', name: 'Kitchen Knife', category: 'Objects & Symbols' },
  { symbol: '🗡️', name: 'Dagger', category: 'Objects & Symbols' },
  { symbol: '⚔️', name: 'Crossed Swords', category: 'Objects & Symbols' },
  { symbol: '🛡️', name: 'Shield', category: 'Objects & Symbols' },
  { symbol: '🚬', name: 'Cigarette', category: 'Objects & Symbols' },
  { symbol: '⚰️', name: 'Coffin', category: 'Objects & Symbols' },
  { symbol: '⚱️', name: 'Funeral Urn', category: 'Objects & Symbols' },
  { symbol: '🏺', name: 'Amphora', category: 'Objects & Symbols' },
  { symbol: '🔮', name: 'Crystal Ball', category: 'Objects & Symbols' },
  { symbol: '📿', name: 'Prayer Beads', category: 'Objects & Symbols' },
  { symbol: '🧿', name: 'Nazar Amulet', category: 'Objects & Symbols' },
  { symbol: '💈', name: 'Barber Pole', category: 'Objects & Symbols' },
  { symbol: '⚗️', name: 'Alembic', category: 'Objects & Symbols' },
  { symbol: '🔭', name: 'Telescope', category: 'Objects & Symbols' },
  { symbol: '🔬', name: 'Microscope', category: 'Objects & Symbols' },
  { symbol: '🕳️', name: 'Hole', category: 'Objects & Symbols' },
  { symbol: '🩹', name: 'Adhesive Bandage', category: 'Objects & Symbols' },
  { symbol: '🩺', name: 'Stethoscope', category: 'Objects & Symbols' },
  { symbol: '💊', name: 'Pill', category: 'Objects & Symbols' },
  { symbol: '💉', name: 'Syringe', category: 'Objects & Symbols' },
  { symbol: '🩸', name: 'Drop of Blood', category: 'Objects & Symbols' },
  { symbol: '🧬', name: 'DNA', category: 'Objects & Symbols' },
  { symbol: '🦠', name: 'Microbe', category: 'Objects & Symbols' },
  { symbol: '🧫', name: 'Petri Dish', category: 'Objects & Symbols' },
  { symbol: '🧪', name: 'Test Tube', category: 'Objects & Symbols' },
  { symbol: '🌡️', name: 'Thermometer', category: 'Objects & Symbols' },
  { symbol: '🧹', name: 'Broom', category: 'Objects & Symbols' },
  { symbol: '🧺', name: 'Basket', category: 'Objects & Symbols' },
  { symbol: '🧻', name: 'Roll of Paper', category: 'Objects & Symbols' },
  { symbol: '🚽', name: 'Toilet', category: 'Objects & Symbols' },
  { symbol: '🚰', name: 'Potable Water', category: 'Objects & Symbols' },
  { symbol: '🚿', name: 'Shower', category: 'Objects & Symbols' },
  { symbol: '🛁', name: 'Bathtub', category: 'Objects & Symbols' },
  { symbol: '🛀', name: 'Person Taking Bath', category: 'Objects & Symbols' },
  { symbol: '🧴', name: 'Lotion Bottle', category: 'Objects & Symbols' },
  { symbol: '🧷', name: 'Safety Pin', category: 'Objects & Symbols' },
  { symbol: '🧸', name: 'Teddy Bear', category: 'Objects & Symbols' },
  { symbol: '🧵', name: 'Thread', category: 'Objects & Symbols' },
  { symbol: '🧶', name: 'Yarn', category: 'Objects & Symbols' },
  { symbol: '🪡', name: 'Sewing Needle', category: 'Objects & Symbols' },
  { symbol: '🪢', name: 'Knot', category: 'Objects & Symbols' },
  { symbol: '🪣', name: 'Bucket', category: 'Objects & Symbols' },
  { symbol: '🪤', name: 'Mouse Trap', category: 'Objects & Symbols' },
  { symbol: '🪥', name: 'Toothbrush', category: 'Objects & Symbols' },
  { symbol: '🪦', name: 'Headstone', category: 'Objects & Symbols' },
  { symbol: '🪧', name: 'Placard', category: 'Objects & Symbols' },
  
  // Symbols & Signs
  { symbol: '🔴', name: 'Red Circle', category: 'Symbols & Signs' },
  { symbol: '🟠', name: 'Orange Circle', category: 'Symbols & Signs' },
  { symbol: '🟡', name: 'Yellow Circle', category: 'Symbols & Signs' },
  { symbol: '🟢', name: 'Green Circle', category: 'Symbols & Signs' },
  { symbol: '🔵', name: 'Blue Circle', category: 'Symbols & Signs' },
  { symbol: '🟣', name: 'Purple Circle', category: 'Symbols & Signs' },
  { symbol: '⚫', name: 'Black Circle', category: 'Symbols & Signs' },
  { symbol: '⚪', name: 'White Circle', category: 'Symbols & Signs' },
  { symbol: '🟤', name: 'Brown Circle', category: 'Symbols & Signs' },
  { symbol: '🔸', name: 'Small Orange Diamond', category: 'Symbols & Signs' },
  { symbol: '🔹', name: 'Small Blue Diamond', category: 'Symbols & Signs' },
  { symbol: '🔶', name: 'Large Orange Diamond', category: 'Symbols & Signs' },
  { symbol: '🔷', name: 'Large Blue Diamond', category: 'Symbols & Signs' },
  { symbol: '🔺', name: 'Red Triangle Pointed Up', category: 'Symbols & Signs' },
  { symbol: '🔻', name: 'Red Triangle Pointed Down', category: 'Symbols & Signs' },
  { symbol: '💠', name: 'Diamond with a Dot', category: 'Symbols & Signs' },
  { symbol: '🔘', name: 'Radio Button', category: 'Symbols & Signs' },
  { symbol: '🔳', name: 'White Square Button', category: 'Symbols & Signs' },
  { symbol: '🔲', name: 'Black Square Button', category: 'Symbols & Signs' },
  { symbol: '⭐', name: 'Star', category: 'Symbols & Signs' },
  { symbol: '🌟', name: 'Glowing Star', category: 'Symbols & Signs' },
  { symbol: '✨', name: 'Sparkles', category: 'Symbols & Signs' },
  { symbol: '⚡', name: 'High Voltage', category: 'Symbols & Signs' },
  { symbol: '💥', name: 'Collision', category: 'Symbols & Signs' },
  { symbol: '💫', name: 'Dizzy', category: 'Symbols & Signs' },
  { symbol: '💦', name: 'Sweat Droplets', category: 'Symbols & Signs' },
  { symbol: '💨', name: 'Dashing Away', category: 'Symbols & Signs' },
  { symbol: '🕳️', name: 'Hole', category: 'Symbols & Signs' },
  { symbol: '💬', name: 'Speech Balloon', category: 'Symbols & Signs' },
  { symbol: '👁️‍🗨️', name: 'Eye in Speech Bubble', category: 'Symbols & Signs' },
  { symbol: '🗨️', name: 'Left Speech Bubble', category: 'Symbols & Signs' },
  { symbol: '🗯️', name: 'Right Anger Bubble', category: 'Symbols & Signs' },
  { symbol: '💭', name: 'Thought Balloon', category: 'Symbols & Signs' },
  { symbol: '💤', name: 'Zzz', category: 'Symbols & Signs' },
  { symbol: '👋', name: 'Waving Hand', category: 'Symbols & Signs' },
  { symbol: '🤚', name: 'Raised Back of Hand', category: 'Symbols & Signs' },
  { symbol: '🖐️', name: 'Hand with Fingers Splayed', category: 'Symbols & Signs' },
  { symbol: '✋', name: 'Raised Hand', category: 'Symbols & Signs' },
  { symbol: '🖖', name: 'Vulcan Salute', category: 'Symbols & Signs' },
  { symbol: '👌', name: 'OK Hand', category: 'Symbols & Signs' },
  { symbol: '🤌', name: 'Pinched Fingers', category: 'Symbols & Signs' },
  { symbol: '🤏', name: 'Pinching Hand', category: 'Symbols & Signs' },
  { symbol: '✌️', name: 'Victory Hand', category: 'Symbols & Signs' },
  { symbol: '🤞', name: 'Crossed Fingers', category: 'Symbols & Signs' },
  { symbol: '🤟', name: 'Love-You Gesture', category: 'Symbols & Signs' },
  { symbol: '🤘', name: 'Sign of the Horns', category: 'Symbols & Signs' },
  { symbol: '🤙', name: 'Call Me Hand', category: 'Symbols & Signs' },
  { symbol: '👈', name: 'Backhand Index Pointing Left', category: 'Symbols & Signs' },
  { symbol: '👉', name: 'Backhand Index Pointing Right', category: 'Symbols & Signs' },
  { symbol: '👆', name: 'Backhand Index Pointing Up', category: 'Symbols & Signs' },
  { symbol: '🖕', name: 'Middle Finger', category: 'Symbols & Signs' },
  { symbol: '👇', name: 'Backhand Index Pointing Down', category: 'Symbols & Signs' },
  { symbol: '☝️', name: 'Index Pointing Up', category: 'Symbols & Signs' },
  { symbol: '👍', name: 'Thumbs Up', category: 'Symbols & Signs' },
  { symbol: '👎', name: 'Thumbs Down', category: 'Symbols & Signs' },
  { symbol: '✊', name: 'Raised Fist', category: 'Symbols & Signs' },
  { symbol: '👊', name: 'Oncoming Fist', category: 'Symbols & Signs' },
  { symbol: '🤛', name: 'Left-Facing Fist', category: 'Symbols & Signs' },
  { symbol: '🤜', name: 'Right-Facing Fist', category: 'Symbols & Signs' },
  { symbol: '👏', name: 'Clapping Hands', category: 'Symbols & Signs' },
  { symbol: '🙌', name: 'Raising Hands', category: 'Symbols & Signs' },
  { symbol: '👐', name: 'Open Hands', category: 'Symbols & Signs' },
  { symbol: '🤲', name: 'Palms Up Together', category: 'Symbols & Signs' },
  { symbol: '🤝', name: 'Handshake', category: 'Symbols & Signs' },
  { symbol: '🙏', name: 'Folded Hands', category: 'Symbols & Signs' },
  { symbol: '✍️', name: 'Writing Hand', category: 'Symbols & Signs' },
  { symbol: '💅', name: 'Nail Polish', category: 'Symbols & Signs' },
  { symbol: '🤳', name: 'Selfie', category: 'Symbols & Signs' },
  { symbol: '💪', name: 'Flexed Biceps', category: 'Symbols & Signs' },
  { symbol: '🦾', name: 'Mechanical Arm', category: 'Symbols & Signs' },
  { symbol: '🦿', name: 'Mechanical Leg', category: 'Symbols & Signs' },
  { symbol: '🦵', name: 'Leg', category: 'Symbols & Signs' },
  { symbol: '🦶', name: 'Foot', category: 'Symbols & Signs' },
  { symbol: '👂', name: 'Ear', category: 'Symbols & Signs' },
  { symbol: '🦻', name: 'Ear with Hearing Aid', category: 'Symbols & Signs' },
  { symbol: '👃', name: 'Nose', category: 'Symbols & Signs' },
  { symbol: '🧠', name: 'Brain', category: 'Symbols & Signs' },
  { symbol: '🫀', name: 'Anatomical Heart', category: 'Symbols & Signs' },
  { symbol: '🫁', name: 'Lungs', category: 'Symbols & Signs' },
  { symbol: '🦷', name: 'Tooth', category: 'Symbols & Signs' },
  { symbol: '🦴', name: 'Bone', category: 'Symbols & Signs' },
  { symbol: '👀', name: 'Eyes', category: 'Symbols & Signs' },
  { symbol: '👁️', name: 'Eye', category: 'Symbols & Signs' },
  { symbol: '👅', name: 'Tongue', category: 'Symbols & Signs' },
  { symbol: '👄', name: 'Mouth', category: 'Symbols & Signs' },
  
  // Nature & Weather
  { symbol: '🌈', name: 'Rainbow', category: 'Nature & Weather' },
  { symbol: '☀️', name: 'Sun', category: 'Nature & Weather' },
  { symbol: '🌞', name: 'Sun with Face', category: 'Nature & Weather' },
  { symbol: '🌝', name: 'Full Moon Face', category: 'Nature & Weather' },
  { symbol: '🌛', name: 'First Quarter Moon Face', category: 'Nature & Weather' },
  { symbol: '🌜', name: 'Last Quarter Moon Face', category: 'Nature & Weather' },
  { symbol: '🌚', name: 'New Moon Face', category: 'Nature & Weather' },
  { symbol: '🌕', name: 'Full Moon', category: 'Nature & Weather' },
  { symbol: '🌖', name: 'Waning Gibbous Moon', category: 'Nature & Weather' },
  { symbol: '🌗', name: 'Last Quarter Moon', category: 'Nature & Weather' },
  { symbol: '🌘', name: 'Waning Crescent Moon', category: 'Nature & Weather' },
  { symbol: '🌑', name: 'New Moon', category: 'Nature & Weather' },
  { symbol: '🌒', name: 'Waxing Crescent Moon', category: 'Nature & Weather' },
  { symbol: '🌓', name: 'First Quarter Moon', category: 'Nature & Weather' },
  { symbol: '🌔', name: 'Waxing Gibbous Moon', category: 'Nature & Weather' },
  { symbol: '🌙', name: 'Crescent Moon', category: 'Nature & Weather' },
  { symbol: '🌎', name: 'Globe Showing Americas', category: 'Nature & Weather' },
  { symbol: '🌍', name: 'Globe Showing Europe-Africa', category: 'Nature & Weather' },
  { symbol: '🌏', name: 'Globe Showing Asia-Australia', category: 'Nature & Weather' },
  { symbol: '🪐', name: 'Ringed Planet', category: 'Nature & Weather' },
  { symbol: '💫', name: 'Dizzy', category: 'Nature & Weather' },
  { symbol: '⭐', name: 'Star', category: 'Nature & Weather' },
  { symbol: '🌟', name: 'Glowing Star', category: 'Nature & Weather' },
  { symbol: '✨', name: 'Sparkles', category: 'Nature & Weather' },
  { symbol: '⚡', name: 'High Voltage', category: 'Nature & Weather' },
  { symbol: '☄️', name: 'Comet', category: 'Nature & Weather' },
  { symbol: '💥', name: 'Collision', category: 'Nature & Weather' },
  { symbol: '🔥', name: 'Fire', category: 'Nature & Weather' },
  { symbol: '🌪️', name: 'Tornado', category: 'Nature & Weather' },
  { symbol: '🌈', name: 'Rainbow', category: 'Nature & Weather' },
  { symbol: '☀️', name: 'Sun', category: 'Nature & Weather' },
  { symbol: '🌤️', name: 'Sun Behind Small Cloud', category: 'Nature & Weather' },
  { symbol: '⛅', name: 'Sun Behind Cloud', category: 'Nature & Weather' },
  { symbol: '🌥️', name: 'Sun Behind Large Cloud', category: 'Nature & Weather' },
  { symbol: '☁️', name: 'Cloud', category: 'Nature & Weather' },
  { symbol: '🌦️', name: 'Sun Behind Rain Cloud', category: 'Nature & Weather' },
  { symbol: '🌧️', name: 'Cloud with Rain', category: 'Nature & Weather' },
  { symbol: '⛈️', name: 'Cloud with Lightning and Rain', category: 'Nature & Weather' },
  { symbol: '🌩️', name: 'Cloud with Lightning', category: 'Nature & Weather' },
  { symbol: '🌨️', name: 'Cloud with Snow', category: 'Nature & Weather' },
  { symbol: '❄️', name: 'Snowflake', category: 'Nature & Weather' },
  { symbol: '☃️', name: 'Snowman', category: 'Nature & Weather' },
  { symbol: '⛄', name: 'Snowman Without Snow', category: 'Nature & Weather' },
  { symbol: '🌬️', name: 'Wind Face', category: 'Nature & Weather' },
  { symbol: '💨', name: 'Dashing Away', category: 'Nature & Weather' },
  { symbol: '💧', name: 'Droplet', category: 'Nature & Weather' },
  { symbol: '💦', name: 'Sweat Droplets', category: 'Nature & Weather' },
  { symbol: '☔', name: 'Umbrella with Rain Drops', category: 'Nature & Weather' },
  { symbol: '☂️', name: 'Umbrella', category: 'Nature & Weather' },
  { symbol: '🌊', name: 'Water Wave', category: 'Nature & Weather' },
  { symbol: '🌫️', name: 'Fog', category: 'Nature & Weather' },
  
  // Celebration & Events
  { symbol: '🎉', name: 'Party Popper', category: 'Celebration & Events' },
  { symbol: '🎊', name: 'Confetti Ball', category: 'Celebration & Events' },
  { symbol: '🎈', name: 'Balloon', category: 'Celebration & Events' },
  { symbol: '🎁', name: 'Wrapped Gift', category: 'Celebration & Events' },
  { symbol: '🎀', name: 'Ribbon', category: 'Celebration & Events' },
  { symbol: '🎂', name: 'Birthday Cake', category: 'Celebration & Events' },
  { symbol: '🍰', name: 'Shortcake', category: 'Celebration & Events' },
  { symbol: '🧁', name: 'Cupcake', category: 'Celebration & Events' },
  { symbol: '🥳', name: 'Partying Face', category: 'Celebration & Events' },
  { symbol: '🎆', name: 'Fireworks', category: 'Celebration & Events' },
  { symbol: '🎇', name: 'Sparkler', category: 'Celebration & Events' },
  { symbol: '✨', name: 'Sparkles', category: 'Celebration & Events' },
  { symbol: '🎄', name: 'Christmas Tree', category: 'Celebration & Events' },
  { symbol: '🎅', name: 'Santa Claus', category: 'Celebration & Events' },
  { symbol: '🤶', name: 'Mrs. Claus', category: 'Celebration & Events' },
  { symbol: '🧑‍🎄', name: 'Mx Claus', category: 'Celebration & Events' },
  { symbol: '🎃', name: 'Jack-O-Lantern', category: 'Celebration & Events' },
  { symbol: '👻', name: 'Ghost', category: 'Celebration & Events' },
  { symbol: '💀', name: 'Skull', category: 'Celebration & Events' },
  { symbol: '☠️', name: 'Skull and Crossbones', category: 'Celebration & Events' },
  { symbol: '🎭', name: 'Performing Arts', category: 'Celebration & Events' },
  { symbol: '🎪', name: 'Circus Tent', category: 'Celebration & Events' },
  { symbol: '🎨', name: 'Artist Palette', category: 'Celebration & Events' },
  { symbol: '🎬', name: 'Clapper Board', category: 'Celebration & Events' },
  { symbol: '🎤', name: 'Microphone', category: 'Celebration & Events' },
  { symbol: '🎧', name: 'Headphone', category: 'Celebration & Events' },
  { symbol: '🎼', name: 'Musical Score', category: 'Celebration & Events' },
  { symbol: '🎵', name: 'Musical Note', category: 'Celebration & Events' },
  { symbol: '🎶', name: 'Musical Notes', category: 'Celebration & Events' },
  { symbol: '🎹', name: 'Musical Keyboard', category: 'Celebration & Events' },
  { symbol: '🥁', name: 'Drum', category: 'Celebration & Events' },
  { symbol: '🎷', name: 'Saxophone', category: 'Celebration & Events' },
  { symbol: '🎺', name: 'Trumpet', category: 'Celebration & Events' },
  { symbol: '🎸', name: 'Guitar', category: 'Celebration & Events' },
  { symbol: '🪕', name: 'Banjo', category: 'Celebration & Events' },
  { symbol: '🎻', name: 'Violin', category: 'Celebration & Events' },
  { symbol: '🎲', name: 'Game Die', category: 'Celebration & Events' },
  { symbol: '♟️', name: 'Chess Pawn', category: 'Celebration & Events' },
  { symbol: '🎯', name: 'Direct Hit', category: 'Celebration & Events' },
  { symbol: '🎳', name: 'Bowling', category: 'Celebration & Events' },
  { symbol: '🎮', name: 'Video Game', category: 'Celebration & Events' },
  { symbol: '🎰', name: 'Slot Machine', category: 'Celebration & Events' },
  { symbol: '🧩', name: 'Puzzle Piece', category: 'Celebration & Events' },
  { symbol: '🪅', name: 'Piñata', category: 'Celebration & Events' },
  { symbol: '🪩', name: 'Mirror Ball', category: 'Celebration & Events' },
  { symbol: '🎗️', name: 'Reminder Ribbon', category: 'Celebration & Events' },
  { symbol: '🎫', name: 'Ticket', category: 'Celebration & Events' },
  { symbol: '🎟️', name: 'Admission Tickets', category: 'Celebration & Events' },
];

const EmojiSearch = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [copiedEmoji, setCopiedEmoji] = useState('');

  // Get unique categories
  const categories = ['All', ...new Set(emojiList.map(emoji => emoji.category))];

  const filteredEmojis = emojiList.filter((emoji) => {
    const matchesSearch = emoji.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         emoji.category.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = selectedCategory === 'All' || emoji.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const copyToClipboard = async (emoji) => {
    try {
      await navigator.clipboard.writeText(emoji.symbol);
      setCopiedEmoji(emoji.symbol);
      setTimeout(() => setCopiedEmoji(''), 2000);
    } catch (err) {
      console.error('Failed to copy emoji:', err);
    }
  };

  return (
    <div className="w-full max-w-6xl mx-auto p-8 bg-white dark:bg-gray-800 rounded-2xl shadow-2xl transition-all duration-300">
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold mb-3 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
          🎯 Professional Emoji Generator
        </h1>
        <p className="text-gray-600 dark:text-gray-300 text-lg">
          Discover and copy from our extensive collection of {emojiList.length}+ professionally curated emojis
        </p>
      </div>

      <div className="mb-6 space-y-4">
        <div className="relative">
          <input
            type="text"
            placeholder="🔍 Search emojis by name or category..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full px-6 py-4 text-lg border-2 border-gray-200 dark:border-gray-600 rounded-xl 
                     focus:outline-none focus:ring-4 focus:ring-blue-500/20 focus:border-blue-500 
                     bg-gray-50 dark:bg-gray-700 dark:text-white
                     transition-all duration-300 shadow-sm hover:shadow-md"
          />
          <div className="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400">
            {searchTerm && (
              <button
                onClick={() => setSearchTerm('')}
                className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"
              >
                ✕
              </button>
            )}
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setSelectedCategory(category)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-200 ${
                selectedCategory === category
                  ? 'bg-blue-500 text-white shadow-lg transform scale-105'
                  : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
              }`}
            >
              {category === 'All' ? '🌟 All Categories' : `${category}`}
            </button>
          ))}
        </div>
      </div>

      {copiedEmoji && (
        <div className="mb-4 p-3 bg-green-100 dark:bg-green-900 border border-green-300 dark:border-green-700 rounded-lg text-center">
          <p className="text-green-800 dark:text-green-200 font-medium">
            ✅ Copied "{copiedEmoji}" to clipboard!
          </p>
        </div>
      )}

      <div className="mb-4 text-center text-gray-600 dark:text-gray-400">
        <p className="text-lg font-medium">
          📊 Showing {filteredEmojis.length} of {emojiList.length} emojis
          {selectedCategory !== 'All' && ` in "${selectedCategory}"`}
        </p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8 xl:grid-cols-10 gap-4">
        {filteredEmojis.map((emoji, index) => (
          <motion.div
            key={`${emoji.symbol}-${index}`}
            className="group relative p-4 border-2 border-gray-200 dark:border-gray-600 rounded-xl 
                     hover:border-blue-400 dark:hover:border-blue-500 cursor-pointer
                     bg-white dark:bg-gray-700 hover:bg-blue-50 dark:hover:bg-gray-600
                     transition-all duration-300 shadow-sm hover:shadow-lg"
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ 
              delay: index * 0.02,
              type: 'spring',
              stiffness: 200,
              damping: 15
            }}
            whileHover={{ 
              y: -8, 
              scale: 1.05,
              transition: { type: 'spring', stiffness: 400, damping: 10 }
            }}
            whileTap={{ scale: 0.95 }}
            onClick={() => copyToClipboard(emoji)}
          >
            <div className="text-center">
              <span className="text-3xl mb-2 block group-hover:scale-110 transition-transform duration-200">
                {emoji.symbol}
              </span>
              <p className="text-xs font-medium text-gray-700 dark:text-gray-300 line-clamp-2 leading-tight">
                {emoji.name}
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                {emoji.category}
              </p>
            </div>
            
            {/* Copy indicator */}
            <div className="absolute inset-0 bg-blue-500/10 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity duration-200 pointer-events-none">
              <div className="absolute top-2 right-2 bg-blue-500 text-white text-xs px-2 py-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                📋 Click to copy
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {filteredEmojis.length === 0 && (
        <div className="text-center py-12">
          <div className="text-6xl mb-4">🔍</div>
          <h3 className="text-xl font-semibold text-gray-700 dark:text-gray-300 mb-2">
            No emojis found
          </h3>
          <p className="text-gray-500 dark:text-gray-400">
            Try adjusting your search terms or selecting a different category
          </p>
        </div>
      )}

      <div className="mt-8 text-center text-sm text-gray-500 dark:text-gray-400">
        <p>💡 <strong>Pro Tip:</strong> Click any emoji to copy it to your clipboard instantly!</p>
        <p className="mt-2">🎨 Professional emoji collection for all your communication needs</p>
      </div>
    </div>
  );
};

export default EmojiSearch;
